version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432

volumes:
  postgres:
